# Generated by Django 2.0.7 on 2018-08-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formall',
            name='book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
