# Generated by Django 2.0.7 on 2018-09-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180810_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formall',
            name='book',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formall',
            name='aka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
