# Generated by Django 2.0.7 on 2018-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180903_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='edit_auth',
            field=models.BooleanField(default=False),
        ),
    ]
