# Generated by Django 2.0.7 on 2019-01-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190107_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formall',
            name='zipcode',
        ),
    ]
