# Generated by Django 2.0.7 on 2019-04-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190107_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='formall',
            name='geom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
