# Generated by Django 2.0.7 on 2019-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190402_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=1)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('subdivisio', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=20, null=True)),
                ('block_numb', models.CharField(blank=True, max_length=10, null=True)),
                ('unit_numbe', models.CharField(blank=True, max_length=10, null=True)),
                ('account_nu', models.CharField(blank=True, max_length=20, null=True)),
                ('l1surnam', models.CharField(blank=True, max_length=32, null=True)),
                ('l2block', models.CharField(blank=True, max_length=10, null=True)),
                ('l3surnum', models.CharField(blank=True, max_length=8, null=True)),
                ('meridian', models.CharField(blank=True, max_length=10, null=True)),
                ('township', models.CharField(blank=True, max_length=10, null=True)),
                ('field_range', models.CharField(blank=True, db_column='_range', max_length=10, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('t_r', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
