# Generated by Django 2.0.7 on 2019-04-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190405_0625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
