# Generated by Django 2.0.7 on 2019-04-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='account_nu',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='block_numb',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='field_range',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='l1surnam',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='l2block',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='l3surnum',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='section',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='subdivisio',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='township',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='unit_numbe',
        ),
        migrations.AddField(
            model_name='tickets',
            name='lot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='plss_section',
            field=models.CharField(blank=True, db_column='_range', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='rural_block',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='rural_section',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='sub_block',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='subdivision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='survey',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
